@JOIN.Services.WebApi_HostAddress = http://localhost:5267
@token = YOUR_JWT_HERE

GET {{JOIN.Services.WebApi_HostAddress}}/api/v1/PersonBusinessProfile/person/3554B06C-9915-4706-8684-F52259FE8D58
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{JOIN.Services.WebApi_HostAddress}}/api/v1/PersonEmployment/person/3554B06C-9915-4706-8684-F52259FE8D58
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{JOIN.Services.WebApi_HostAddress}}/api/v1/PersonFinancialProfile/person/3554B06C-9915-4706-8684-F52259FE8D58
Authorization: Bearer {{token}}
Accept: application/json

###
